export enum Names {
  MD = "Измеренная по стволу глубина",
  TVD = "Вертикальная глубина",
  tubing_d = "Диаметр трубы (tubing)",
  casing_d = "Диаметр трубы (casing)",
  h_mes = "Глубина спуска НКТ",
  wct = "Обводненность",
  rp = "Газовый фактор",
  gamma_oil = "Отн. плотность нефти",
  gamma_gas = "Отн. плотность газа",
  gamma_wat = "Отн. плотность воды",
  t_res = "Температура резервуара", //Пластовая температура
  inclinometry = "Инклинометрия",
  casing = "Данные по ЭК",
  tubing = "Данные по НКТ",
  pvt = "PVT",
  p_wh = "Буферное давление",
  geo_grad = "Градиент температуры",
  h_res = "Глубина Верхних Дыр Перфорации",
  pi = "Индекс продуктивности",
  p_res = "Давление резервуара",
  p_wf = "",
}

export enum Metrics {
  MD = "м",
  TVD = "м",
  tubing_d = "м",
  casing_d = "м",
  h_mes = "м",
  wct = "%",
  rp = "м3/т",
  gamma_oil = "",
  gamma_gas = "",
  gamma_wat = "",
  t_res = "C",
  inclinometry = "",
  casing = "",
  tubing = "",
  pvt = "PVT",
  p_wh = "атм",
  geo_grad = "C/100 м",
  h_res = "м",
  pi = "м3/сут/бар",
  p_res = "бар",
  p_wf = "",
}
